#source("http://bioconductor.org/biocLite.R")
#biocLite("ArrayTools")

#WARNING: the .cls generated by the function createGSEAFiles is wrong. Check it out and modify for your purpose.

library("affy")
library("limma")
library("genefilter")
library("ArrayTools")
library("annotate")

source("source/differentialExpression.R")
source("source/normalizeData.R")
source("source/anotateBestGenes.R")

#You can find this data in http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18198


fileDirs <- list.dirs(path = './data/RawData', recursive = FALSE)

targets <- list(readTargets("./data/RawData/GSE18198_RAW/targets.txt", row.names="FileName"))
targets <- list(targets, readTargets("./data/RawData/GSE18351_RAW/targets.txt", row.names="FileName"))
targets <- list(targets, readTargets("./data/RawData/GSE18198_RAW_KOPT-K1/targets.txt", row.names="FileName"))
targets <- list(targets, readTargets("./data/RawData/GSE18198_RAW_T_ALL/targets.txt", row.names="FileName"))


# Caso 18198 all cell lines --------------------------------------------------------------

#change this to see what we are looking for
design18198 <-cbind(Control=c(1,1,1,1,1,1,0,0,0,0,0,0), Cases=c(0,0,0,0,0,0,1,1,1,1,1,1))
#design18198<-cbind(Control=c(1,1,1,0,0,0,1,1,1,0,0,0), Cases=c(0,0,0,1,1,1,0,0,0,1,1,1))

rownames(design18198)<-targets[1]$FileName

cont.matrix18198 <- makeContrasts(CasesvsControl=Cases-Control,levels=design18198)

data18198 <- normalizeData(fileDirs[1])

dataDiff18198 <- differentialExpression(targets[1], data18198, design18198, cont.matrix18198)

setwd("~/MScBioinformatics/TranscriptomicAnalysis/data/RawData/GSE18198_RAW/")

createGSEAFiles(eSet = data18198[rownames(dataDiff18198)], catVar="sample")

setwd("~/MScBioinformatics/TranscriptomicAnalysis")

#output.gct(normal, filename = "probe")

# Caso 18198 KOPT K1 --------------------------------------------------------------

#change this to see what we are looking for
design <- cbind(Control=c(1,1,1,0,0,0), Cases=c(0,0,0,1,1,1))

rownames(design)<-targets[3]$FileName

cont.matrix18198K1 <- makeContrasts(CasesvsControl=Cases-Control,levels=design)

data18198K1 <- normalizeData(fileDirs[2])

dataDiff18198K1 <- differentialExpression(targets[3], data18198K1, design, cont.matrix18198K1)

finalGenesK1 <- anotateBestGenesHuman(data18198K1, dataDiff18198K1, 0.01)

annotationsGenesK1 <- unique(finalGenesK1)

writeLines(annotationsGenesK1, "data/RawData/GSE18198_RAW_KOPT-K1/annotationsGenes.txt")

finalGenesK1[finalGenesK1=="HDAC9"]

dataDiff18198K1[rownames(dataDiff18198K1)=="1552760_at", ]

finalGenesK1["209921_at"] #Debería estar

finalGenesK1["1552760_at"] #No debería estar

# Caso 18198 HPB ALL --------------------------------------------------------------

#change this to see what we are looking for
design <- cbind(Control=c(1,1,1,0,0,0), Cases=c(0,0,0,1,1,1))

rownames(design18198)<-targets[4]$FileName

cont.matrix18198ALL <- makeContrasts(CasesvsControl=Cases-Control,levels=design)

data18198ALL <- normalizeData(fileDirs[3])

dataDiff18198ALL <- differentialExpression(targets[4], data18198ALL, design, cont.matrix18198ALL)

finalGenesALL <- anotateBestGenesHuman(data18198ALL, dataDiff18198ALL, 0.01)

annotationsGenesALL <- unique(finalGenesALL)

writeLines(annotationsGenesALL, "data/RawData/GSE18198_RAW_T_ALL/annotationsGenes.txt")

finalGenesALL[finalGenesALL=="HDAC9"]

dataDiff18198ALL[rownames(dataDiff18198ALL)=="1552760_at", ]

# Caso 18351 --------------------------------------------------------------

design18351 <- cbind(Control=c(1,1,1,0,0,0), Cases=c(0,0,0,1,1,1))

rownames(design18351) <- targets[2]$FileName

cont.matrix18351 <- makeContrasts(CasesvsControl=Cases-Control,levels=design18351) 

data18351 <- normalizeData(fileDirs[4])

#Volver a comprobar esta expresión diferencial con babelomics, geneToR, asterias...
dataDiff18351 <- differentialExpression(targets[2], data18351, design18351, cont.matrix18351)



#Probar esto
#design = cbind(mean=1,diff=cl)  		##generamos la matriz de diseño
#fit = lmFit(exprs(ALL),design)			##ajustamos el modelo lineal con los datos de ALL segun matriz de diseño
#fit2 = eBayes(fit)						##test bayesiano sobre el modelo lineal ajustado
#res<-topTable(fit2, coef="diff", adjust.method = "fdr", sort.by="p")  ##salida de resultados

#data18351[rownames(dataDiff18351)]

setwd("~/MScBioinformatics/TranscriptomicAnalysis/data/RawData/GSE18351_RAW/")

createGSEAFiles(eSet = data18351[rownames(dataDiff18351)], catVar="sample")

setwd("~/MScBioinformatics/TranscriptomicAnalysis")
